describe('Netflx web', () => {
  it('searches for a serie, opens its dialog and closes it', () => {
    cy.visit('/')
    cy.get('button[aria-label="Search"]').click()
    cy.get('#query').type('The Walking Dead')
    cy.get('section[aria-label="Grid of shows"]')
      .within(() => {
        cy.get('img[alt="The Walking Dead"]')
          .first()
          .as('theWalkingDeadCard')
          .should('be.visible')
        cy.get('@theWalkingDeadCard')
          .click({ force: true })
      })
    cy.contains('div[role="dialog"] p', "Sheriff's deputy Rick Grimes")
      .as('movieDialog')
      .should('be.visible')
    cy.contains('span', 'Close')
      .parent()
      .as('closeButton')
    cy.get('@closeButton').click()
    cy.get('@movieDialog').should('not.exist')
  })
})
